import { StyleSheet } from 'react-native';
import { COLORS } from '../../theme/color';

export const styleAddtree = StyleSheet.create({
  container: {
    flex: 1,
    height: '100%',
    alignItems: 'center',
    marginTop: 16,
  },
  headSession: {
    flexDirection: 'row',
    width: '90%',
    height: 40,
    alignItems: 'center',
  },
  headSessionModal: {
    flexDirection: 'row',
    width: '100%',
    maxHeight: '100%',
    paddingRight: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#E9E9E9',
  },

  txtTitle: {
    fontSize: 20,
    color: '#163859',
    lineHeight: 28,
    textAlign: 'center',
    fontFamily: 'Nunito-Bold',
  },

  txtContainer: {
    height: 40,
    width: '100%',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },

  txtTitleModal: {
    fontSize: 20,
    lineHeight: 27,
    letterSpacing: 0,
    textAlign: 'center',
    color: COLORS.blue,
    fontFamily: 'Nunito-Bold',
  },
  txtTitleModal1: {
    fontSize: 20,
    lineHeight: 27,
    letterSpacing: 0,
    textAlign: 'center',
    color: COLORS.green,
    fontFamily: 'Nunito-Bold',
  },
  txtTitleModal2: {
    fontSize: 20,
    lineHeight: 27,
    letterSpacing: 0,
    textAlign: 'center',
    color: COLORS.red,
    fontFamily: 'Nunito-Bold',
  },
  inputSession: {
    padding: 16,
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 16,
    borderRadius: 15,
    shadowColor: '#000',
    elevation: 4,
    shadowOpacity: 0.2,
    shadowRadius: 3,
    shadowOffset: { width: -2, height: 4 },
    backgroundColor: '#fff',
  },
  btnSendSession: {
    marginTop: 16,
    height: 48,
    backgroundColor: COLORS.blue,
    borderRadius: 10,
    borderWidth: 1,
    marginBottom: 32,
  },
  btnSendSession1: {
    marginTop: 16,
    height: 48,
    backgroundColor: COLORS.green,
    borderRadius: 10,
    marginBottom: 32,
  },
  btnSendSession2: {
    marginTop: 16,
    height: 48,
    backgroundColor: COLORS.red,
    borderRadius: 10,
    marginBottom: 32,
  },
  btnSendSession3: {
    marginTop: 16,
    height: 48,
    backgroundColor: COLORS.grey,
    borderRadius: 10,
    marginBottom: 32,
  },
  txtBtnSignup: {
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  root: {
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 16,
  },
  group8183: {
    width: 80,
    height: 80,
  },
  photo: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 16,
    fontStyle: 'normal',
    fontFamily: 'Nunito-Bold',
  },
  hoverButtonFull: {
    width: 143,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  frame625074: {
    width: 143,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    backgroundColor: '#163859',
    flexDirection: 'row',
    borderRadius: 12,
  },
  frame625079: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  btnSession: {
    height: 48,
    backgroundColor: '#163859',
    borderRadius: 10,
    borderWidth: 1,
    flex: 1,
  },
  txtBtn: {
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
});

export const stylesFarmname = StyleSheet.create({
  container: {
    flex: 1,
    height: '100%',
    alignItems: 'center',
    marginTop: 16,
  },
  headSession: {
    flexDirection: 'row',
    width: '90%',
    height: 40,
    alignItems: 'center',
  },
  txtTitle: {
    fontSize: 20,
    color: '#163859',
    lineHeight: 28,
    textAlign: 'center',
    fontFamily: 'Nunito-Bold',
  },
  inputSession: {
    width: '90%',
    padding: 16,
    borderRadius: 12,
    backgroundColor: 'white',
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  btnSession: {
    height: 48,
    backgroundColor: '#163859',
    borderRadius: 10,
    borderWidth: 1,
    width: '90%',
  },
  txtBtn: {
    justifyContent: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
});
